### ISSUE TITLE
PHP verison 7 cannot install this package

### ISSUE THREAD

**Issue by amruthalalm** [wearesho-team/yii2-recaptcha-v3#11]
While installing through php 7 getting this message                                                                               
  [InvalidArgumentException]                                                   
  Package wearesho-team/yii2-recaptcha-v3 at version ^1.1 has a PHP requireme  
  nt incompatible with your PHP version (7.0.33)

**Comment by KartaviK** [comment]
@amruthalalm In composer.json said that minimal required version of php is ^7.1. You need to upgrade php on your machine

**Comment by Horat1us** [comment]
@amruthalalm PHP 7.0 is not supported. Please install PHP 7.4 to use our packages.
